site_name: Documentation Spring Boot
theme:
  name: material
nav:
  - Accueil: docs/index.md
  - Architecture: docs/architecture.md
  - API: docs/api.md
  - Configuration: docs/configuration.md
  - Historique des commits: docs/commits.md
